### ISSUE TITLE
Dudas...

### ISSUE THREAD

**Issue by kimvex** [AdrianArroyoCalle/node-xulrunner#36]
Disculpa si estoy abriendo un issue para hacer esta pregunta.

¿Este proyecto es para ejecutar una aplicion web como si fuera nativo, algo asi como electron?

O en si para que es, es que me intriga bastante.

**Comment by aarroyoc** [comment]
El proyecto era un intento de tener algo parecido a node-webkit (ni Atom ni Electron existían todavía) pero con el motor de Firefox. El proyecto más o menos funcionaba pero hace tiempo que no lo pruebo. Realmente funciona más tipo node-webkit, sigues teniendo un servidor y un cliente, aunque se ejecuten a la vez cuando arranques el programa.
